 $('.picone').click(function(){
 	$('.picone').hide();
 	$('.pictwo').show();
 	$('.leftdown>ul').slideUp();
 })
  $('.pictwo').click(function(){
 	$('.picone').show();
 	$('.pictwo').hide();
 	$('.leftdown>ul').slideDown();
 })
  $('.leftdown>p').hover(function(){
  	$(this).css("background","rgb(29,174,42)").siblings('.leftdown>p').css("background","white");
  },function(){
  	$('.leftdown>p').css("background","white");
  })
  $('.leftdown>ul>li').hover(function(){
  	$(this).css("background","rgb(29,174,42)").siblings('.leftdown>ul>li').css("background","white");
  },function(){
  	$('.leftdown>ul>li').css("background","white");
  })
